<<<<<<< HEAD
version: "2"
services:
    web:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: tabel
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
volumes:
    persistent:
=======
web:
   image: php:7.2-apache
   environment:
     - ALLOW_OVERRIDE=true
   ports:
     - "80:80"
   links:
     - db
   volumes:
     - ./apps:/var/www/html/

db:
  image: mariadb
  restart: always
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: admin
    MYSQL_PASSWORD: test
    MYSQL_DATABASE: database
  ports:
    - "8889:3306"
>>>>>>> 2d21bbef73a6420bb32ad060d92638d8e23ada05
